name: Terraform Apply

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

  setup-terraform:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.3

  terraform-init:
    runs-on: ubuntu-latest
    needs: setup-terraform
    steps:
      - name: Terraform Initialize
        run: terraform init
        working-directory: environments/prod

  terraform-validate:
    runs-on: ubuntu-latest
    needs: terraform-init
    steps:
      - name: Terraform Validate
        run: terraform validate
        working-directory: environments/prod

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-validate
    steps:
      - name: Terraform Plan
        run: terraform plan -no-color -var="sql_administrator_login_password=${{ secrets.SQL_ADMIN_LOGIN_PASS }}"
        working-directory: environments/prod

  terraform-apply:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: terraform-plan
    steps:
      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color -var="sql_administrator_login_password=${{ secrets.SQL_ADMIN_LOGIN_PASS }}"
        working-directory: environments/prod
